spring:
  application:
    name: stock-streaming-data-pipeline-api
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
    url: ${DB_URI}

  cassandra:
    contact-points: ${CASSANDRA_HOST}
    port: 9042
    local-datacenter: dc1
    keyspace-name: ${CASSANDRA_KEYSPACE}
    username: ${CASSANDRA_USERNAME}
    password: ${CASSANDRA_PASSWORD}
    request:
      timeout: 30s

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080