apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-namespace
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-config
  namespace: pipeline-namespace
data:
  FINNHUB_STOCKS_TICKERS: '["AAPL", "GOOG", "AMZN"]'  # TODO: Update to your stock tickers
  FINNHUB_VALIDATE_TICKERS: "1"

  KAFKA_SERVER: "kafka-service.pipeline-namespace.svc.cluster.local"
  KAFKA_PORT: "9092"
  KAFKA_TOPIC_NAME: "market"
  KAFKA_MIN_PARTITIONS: "1"

  SPARK_MASTER: "spark://spark-master:7077"
  SPARK_MAX_OFFSETS_PER_TRIGGER: "100"
  SPARK_SHUFFLE_PARTITIONS: "2"
  SPARK_DEPRECATED_OFFSETS: "False"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pipeline-pdb
  namespace: pipeline-namespace
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: pipeline