apiVersion: apps/v1
kind: Deployment
metadata:
  name: finnhubproducer
  namespace: pipeline-namespace
  labels:
    k8s.service: finnhubproducer
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s.service: finnhubproducer
  template:
    metadata:
      labels:
        k8s.network/pipeline-network: "true"
        k8s.service: finnhubproducer
    spec:
      containers:
        - name: finnhubproducer
          image: public.ecr.aws/d7v9d9b4/stock-streaming-data-pipeline/finnhub-producer:latest
          envFrom:
            - configMapRef:
                name: pipeline-config
            - secretRef:
                name: pipeline-secrets
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: finnhubproducer
  namespace: pipeline-namespace
  labels:
    k8s.service: finnhubproducer
spec:
  clusterIP: None
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
  selector:
    k8s.service: finnhubproducer
