apiVersion: v1
kind: Secret
metadata:
  name: pipeline-secrets
  namespace: pipeline-namespace
type: Opaque
data:
  FINNHUB_API_TOKEN: "Y3VkM29rMXIwMXFpZ2VicHV0dGdjdWQzb2sxcjAxcWlnZWJwdXR1MA=="   # Encode into Base64
  CASSANDRA_USER: "Y2Fzc2FuZHJh"      # Encode into Base64
  CASSANDRA_PASSWORD: "Y2Fzc2FuZHJh"  # Encode into Base64
