apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: spark
  namespace: pipeline-namespace
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: spark-on-k8s
    meta.helm.sh/release-namespace: spark-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: pipeline-namespace
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: spark-on-k8s
    meta.helm.sh/release-namespace: spark-operator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: pipeline-namespace
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: spark-on-k8s
    meta.helm.sh/release-namespace: spark-operator
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: pipeline-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-role
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: spark-token
  namespace: pipeline-namespace
  annotations:
    kubernetes.io/service-account.name: "spark"