apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: pipeline-namespace
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: spark-on-k8s
    meta.helm.sh/release-namespace: spark-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: pipeline-namespace
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: spark-on-k8s
    meta.helm.sh/release-namespace: spark-operator
rules:
  - verbs:
      - "*"
    apiGroups:
      - "*"
    resources:
      - pods
  - verbs:
      - "*"
    apiGroups:
      - "*"
    resources:
      - services

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: pipeline-namespace
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: spark-on-k8s
    meta.helm.sh/release-namespace: spark-operator
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: pipeline-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-role