apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-db-volume-0
  labels:
    type: local
    app: cassandra-db
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/cassandra-db-volume-0
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-volume-0
  labels:
    type: local
    app: kafka
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/kafka-volume-0
    type: DirectoryOrCreate