{
 "title": "Dashboard for Stock Items",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": true,
 "templating": {
  "list": [
   { "name": "symbol", "query": "AAPL,AMZN,GOOG" }
  ]
 },
 "panels": [
  { "title": "${symbol} Stock Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "${symbol} 가격",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "select symbol, price, trade_timestamp from trades where symbol = '${symbol}' and trade_timestamp>$__timeFrom and trade_timestamp<$__timeTo;\n\n\n"
    }
   ]
  },
  {
   "title": "Average price*volume from last 15 seconds",
   "type": "table",
   "gridPos": { "h": 20, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "target": "select symbol, price_volume_multiply, ingest_timestamp from running_averages_15_sec where symbol='${symbol}';"
    }
   ]
  },
  {
   "title": "${symbol} Volume",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 11 },
   "targets": [
    {
     "target": "select symbol, volume, trade_timestamp from trades where symbol = '${symbol}' and trade_timestamp>$__timeFrom and trade_timestamp<$__timeTo;"
    }
   ]
  }
 ]
}